### ISSUE TITLE
Porting Steam game server binaries to ARM 64 TV boxes ( Amlogic) !

### ISSUE THREAD

**Issue by siliconhippy** [AndreRH/hangover#116]
## System Details

Amlogic S905, S905X, S905W ARM64 ( tv boxes) running Armbian.com Linux.

## Problems Description

I would like to port Steam game server binaries to an Amlogic tv box as above.

Is this generally possible, and easier than porting the client game titles ?

Will it be easier to port Linux than Windows binaries for Steam game servers?

Any suggestions on how to go about it, including a cross compiling platform ?

Thanks ! ☺️😸🤔

**Comment by stefand** [comment]
Your best bet is to run the Linux binaries in qemu-linux-user for now. Hangover might work, but since the server binaries don't need 3D graphics and have Linux binaries available it doesn't have any real advantages over its Linux cousin.

I'm going to close this ticket though because the question is more a generic user support question than anything related to the development of this relatively Alpha software...
