### ISSUE TITLE
try to add screen reader accessible .exe app browser dialog window

### ISSUE THREAD

**Issue by JanuszChmiel** [AndreRH/hangover#125]
I Am running on ANdroid 8.0

## Problems Description
I would like to kindly ask you, if somebody of you could add accessible app browse button. Which would allow screen reader users to choose .exe app from Android device? Or if it would be possible to register Hangover so if file manager from Android would try to open .exe app, Hangover could automatically launch .exe app?
I know, that even official Wine do not contain such code. BUt may be, that it could be implemented.

Thank you very much for yours answer.
I Am using latest available Android accessibility suite. There are many audio games, which could be executed by using this project. Those games are based on BGT special game creation engine based on C++ language. I have tried ExaGear but there was timer based issues and sound issues. Key reaction speed have been very slow even if user hold some key so system could auto repead some key press.
So I want to try your project. By other words. I would like to use games based only on audio, Those games do not use graphics at all. May be that you could look at your code so it would be optimised for games created by using BGT.
Here is one very professionally made game with no violence at all so you could look at it safely.
http://www.ndadamson.com/get-tubesim-portable.php
It is very non easy to use Wine GUI without screen reader and type long paths names with .exe without feetback. Park boss game is also strategical game.
Thank you very much for your time and for your help.

**Comment by AndreRH** [comment]
Hi,
Hangover on Android is not supported anymore, so there'll be no changes to it anymore.

**Comment by JanuszChmiel** [comment]
Oh it is so sad.
And do you think, that there is some chance to run X86 Windows APPS by using Android kernel? Russian programmers have introduced Exagear simulator, but I do not know if it will be available because it is not available on Play store.
I have tried to use Box and Termux and some Linux distro executed by using Proot. But I do not know, how it will works.

**Comment by Heasterian** [comment]
@AndreRH Could you help with wrapping Android specific libs like libhardware and libandroid and their dependencies in box86? It's probably one of few missing things that prevents modded i386 Wine apk with box86 included from working. Afaik, you was one of guys working on wineandroid.drv.so, that's why I'm asking.

Modded apk builder that should build i386 Wine with box86 for Android (without dynarec enabled for now) is here: https://github.com/Heasterian/WineBox86.apk
I'll probably upload i386 Android libs that are not wrapped soon to be included in apk so it will try to run emulating them, but it still can't start display or audio with them. cmd.exe runs fine in shell tho.
