### ISSUE TITLE
Is this for 64 apps only?

### ISSUE THREAD

**Issue by DOOMMARINE117** [AndreRH/hangover#138]
can you also install on linux with 32 apps too? or is it just 64 apps?

is this arm exclusive?

**Comment by AndreRH** [comment]
From the README:

> ...to run (x86_64)/x86_32 Windows applications on aarch64/(ppc64le)/x86_64 Wine. (Architectures in brackets are currently not supported)

You currently can run 32-bit Windows apps on AMD64 and ARM64. For combinations in brackets you can use older Hangover versions before 0.8

**Comment by hackgrid** [comment]
The latest release mentions Box64 and FEX integration.
I thought Box64 is for x86_64 applications on ARM64.

So why do you only support 32bit apps? I would have thought you only support 64bit apps because of Box64, no 32 bit apps (you would need Box86 for this, correct?)

Or do you use Box86 only atm? (is there Box32 already?)

**Comment by hackgrid** [comment]
Maybe you should remove that whole text-in-brackets-things completly?
Far too confusing, the Phoronix article got it wrong as well!

I guess you supported 64bit with qemu before 0.8.x?

Maybe add the past x64 support only at the end of your readme, I mean 0.6.5 was released ago 2 years+ ...

**Comment by AndreRH** [comment]
Done
