### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by AllPlatform** [AndreRH/hangover#41]
please if you can help me
I am trying to run winrar32.exe setup But nothing happened This is my code :
Wineconsole.exe
C:
cd c:\x86
c:\x86\qemu-x86-64.exe.so c:\x86\winrar.exe 
I copied the file to x86 folder 
I am sure my phone is architecture aarch64
Thank if you feedback

**Comment by stefand** [comment]
Are you trying to run this on android?

Try running winrar.exe directly, without prefixing it with qemu. Wine will automatically figure out to use qemu for x86 binaries.

**Comment by AllPlatform** [comment]
![Screenshot_2019-11-19-07-28-47-358_org andrerh hangover](https://user-images.githubusercontent.com/44525248/69250856-07872300-0be3-11ea-886e-3e41f6808b05.jpg)
Thank Feedback 
but I Can't Run X86 Binaries

**Comment by AllPlatform** [comment]
> Are you trying to run this on android?
> 
> Try running winrar.exe directly, without prefixing it with qemu. Wine will automatically figure out to use qemu for x86 binaries.

Pls feedback

**Comment by akovacs** [comment]
If you are running hangover-0.4.0, then the red error box with the filename appears since it tries to run the x86 binary without qemu. 

> err:process:create_process L"C:\\x86\\YourBinary.exe" not supported on this installation (x86 binary)

You will need to run the binary using qemu and enable logging in wine to troubleshoot. First, adb into the device. Enable logging using the following commands:

    adb shell
    run-as org.andrerh.hangover
    echo "warn+all,+seh,+relay" > files/winedebug

Then connect a bluetooth keyboard to your device, start Hangover, and run the following in the Wine Command Prompt:

    c:
    cd c:\x86\qemu_guest_dll32
    c:\x86\qemu-x86_64.exe.so c:\x86\fj\YourBinary.exe
    
Finally, pull the logs from your device (you might need root to do this) and search for YourBinary.exe inside them:

    adb shell
    su
    cp /data/data/org.andrerh.hangover/files/log /sdcard/wine.log
    exit
    adb pull /sdcard/wine.log .

**Comment by AndreRH** [comment]
ARM64 Android is abandoned for now
