### ISSUE TITLE
About script in gen branch

### ISSUE THREAD

**Issue by hmilyyang** [AndreRH/hangover#44]
I try to use the python script in the gen branch to generate some API defination, but it seems than the script is old, and it try to write some ".def" file. Is there any new version of the gen script. 
And thanks for great work! I'm trying to adapt some more apps to run.

**Comment by stefand** [comment]
Nah, unfortunately not, just create an empty .def file.

Improvements to the script would be very welcome; Unfortunately I have pretty much no time for hangover lately.

**Comment by stefand** [comment]
I forgot to mention, as you can see in the existing DLLs, use a .spec file (usually copied from the Wine DLL) to handle DLL exports. The .def file was okish for 64 bit only DLLs, but for 32 bit (and in particular for handling both 64 and 32 bit from the same input) the calling convention and parameter info is essential because 32 bit exports have a sort of name mangling.

**Comment by hmilyyang** [comment]
So the .spec file has to be manuelly created? I think it should be easy to generate by script. I will do some work on it.
The other problem is that structs thunking has to be done manuelly, and I think it is possible to be generated by script.

**Comment by AndreRH** [comment]
work on it would be appreciated
