### ISSUE TITLE
submodule fail

### ISSUE THREAD

**Issue by cloud9350** [AndreRH/hangover#5]
![screenshot from 2018-07-11 07-54-55](https://user-images.githubusercontent.com/5405019/42580632-f16226e2-8565-11e8-8b7a-f5cbe1776ec7.png)

Android NDK, Tools, sysroot, wine build, qemu build and set path done.
However, the error still occurs.

**Comment by stefand** [comment]
I'll have to yield to André on this one - I've never built the android build myself :-\ .

Can you attach build.android/libpng-1.5.30/config.log ? It should contain a more detailed explanation why the C compiler doesn't work.

**Comment by cloud9350** [comment]
@stefand I found "aarch64-linux-android-clang command not found" message. Thanks.
But I have another problem
```
gureumi@ubuntu:~/Desktop/hangover$ git submodule update
fatal: reference is not a tree: fdcf4e3acc64f6afce9720f751aec990dcc76a38
Unable to checkout 'fdcf4e3acc64f6afce9720f751aec990dcc76a38' in submodule path 'wine'
gureumi@ubuntu:~/Desktop/hangover$ 
```
I opened the wine folder and it was empty.

**Comment by stefand** [comment]
Hmm, that was probably my mistake. I sometimes forget to push some of the trees, or I look at what I am doing with git push --dry-run and then forget to do the actual push.

I've pushed what I have locally and made sure git submodule update works. Do a fetch and try again. Note though that I haven't yet tried to build the recent rebase of wine and qemu.

**Comment by cloud9350** [comment]
@stefand Work now. thanks answer!

**Comment by cloud9350** [comment]
@stefand 
```
gureumi@DESKTOP-U63LTE8:~/hangover$ git log -1 wine
commit e55e33467a83caad6d3cc6183a2c6b53dcc710c7
Author: Stefan Dösinger <stefan@codeweavers.com>
Date:   Mon Jul 16 08:59:49 2018 +0200

    Rebase submodules
gureumi@DESKTOP-U63LTE8:~/hangover$ git log -1 qemu
commit e55e33467a83caad6d3cc6183a2c6b53dcc710c7
Author: Stefan Dösinger <stefan@codeweavers.com>
Date:   Mon Jul 16 08:59:49 2018 +0200

    Rebase submodules
gureumi@DESKTOP-U63LTE8:~/hangover$ ls
dlls  glib  libiconv  libxml2  libxslt  Makefile  Makefile.android  qemu  README  wine
gureumi@DESKTOP-U63LTE8:~/hangover$ cd wine
gureumi@DESKTOP-U63LTE8:~/hangover/wine$ ls
gureumi@DESKTOP-U63LTE8:~/hangover/wine$ cd ..
gureumi@DESKTOP-U63LTE8:~/hangover$ git submodule update
fatal: reference is not a tree: 066c1658a73473550717787b8e35c6d390a8dea9
fatal: reference is not a tree: aec4b1f16cfdf19f9db7e4984dd5b2e36864f3ec
Unable to checkout '066c1658a73473550717787b8e35c6d390a8dea9' in submodule path 'qemu'
Unable to checkout 'aec4b1f16cfdf19f9db7e4984dd5b2e36864f3ec' in submodule path 'wine'
gureumi@DESKTOP-U63LTE8:~/hangover$
```

**Comment by stefand** [comment]
Try again. It seems that the interaction between force pushes and submodules and the github servers don't quite do what I expected.

I rebased Wine and Qemu and pushed those to make sure I don't forget, but wanted to wait with updating the top level references until I knew it would build OK. I thought those two pushes wouldn't cause any harm, but apparently github refuses to give you the old commits. If my reading is right that also means you'll have a hard time checking out an old revision that you didn't by luck fetch earlier :-\ .

Maybe it is time to switch to merging in changes from wine and qemu instead of rebasing. I like to have the easy-to-see surplus patches compared to upstream, but rebases cause so much pain in other ways.

**Comment by cloud9350** [comment]
🤔
Working now.

**Comment by XeGrox** [comment]
I'm still getting the exact same errors here in 2019, is there anything I missed out?
