### ISSUE TITLE
I cannot run notepad++

### ISSUE THREAD

**Issue by peasoft** [AndreRH/hangover#71]
When I run notepad++,it will display this:
![Screenshot_2020-05-30-12-00-30-82](https://user-images.githubusercontent.com/55051861/83319044-50dcbd00-a26d-11ea-8061-4d5df5a615d1.png)
Why I can't run it?Is this a bug?

**Comment by peasoft** [comment]
And I can't run C:\x86\qemu-x86_64.exe.so,
![Screenshot_2020-05-30-12-14-07-16](https://user-images.githubusercontent.com/55051861/83319228-170cb600-a26f-11ea-97b0-61e6ee1f857e.png)

**Comment by ric96** [comment]
I get this error:

```
[ric@localhost hangover]$ build/wine-host/loader/wine build/qemu/x86_64-windows-user/qemu-x86_64.exe.so ~/.wine/drive_c/Notepad++/notepad++.exe 
0050:fixme:x11settings:X11DRV_ChangeDisplaySettingsEx Changing non-primary adapter L"\\\\.\\DISPLAY2" settings is currently unsupported.
00b8:fixme:x11settings:X11DRV_ChangeDisplaySettingsEx Changing non-primary adapter L"\\\\.\\DISPLAY2" settings is currently unsupported.
32 bit environment set up, Large Address Aware: NO.
Segmentation fault (core dumped)

```

regular notepad works fine.

**Comment by stefand** [comment]
Hmm, a plain segmentation fault seems weird. Normally at least Wine's debugger should kick in.

I'd suggest to try to run it in gdb either with

```
gdb build/wine-host/loader/wine
start build/qemu/x86_64-windows-user/qemu-x86_64.exe.so ~/.wine/drive_c/Notepad++/notepad++.exe

```
It may help to delete wine-host/loader/wine-preloader to run through the regular dynamic library loader. Otherwise extra tricks are needed to get debug symbols in gdb.

Or try winedbg:

```
build/wine-host/loader/wine winedbg build/qemu/x86_64-windows-user/qemu-x86_64.exe.so ~/.wine/drive_c/Notepad++/notepad++.exe
c
```

And see if either of them gives useful exception info.

**Comment by AndreRH** [comment]
irrelevant with new Hangover approach
