### ISSUE TITLE
NTDLL Build failed __sync_bool_compare_and_swap_16

### ISSUE THREAD

**Issue by TuxThePenguin0** [AndreRH/hangover#72]
Hardware: Pinebook Pro
Packages:
```
$ uname -a
Linux Opal 5.7.0-ARCH-ARM+ #1 SMP Thu Jun 4 21:52:33 AEST 2020 aarch64 GNU/Linux
$ pacman -Q `pacman -Qsq mingw-`
mingw-w64-binutils 2.34-1
mingw-w64-crt 7.0.0-1
mingw-w64-gcc 9.2.0-1
mingw-w64-headers 7.0.0-1
mingw-w64-winpthreads 7.0.0-1
```
An error in rtl.c when building ntdll, build has been tried with both single and multi-threading so that shouldn't be the issue. Possibly GCC 9.2 being too old?
```
/usr/bin/ld: rtl.o: in function `RtlInterlockedFlushSList':
/home/tux/Repos/hangover/build/wine-host/dlls/ntdll/../../../../wine/dlls/ntdll/rtl.c:121: undefined reference to `__sync_bool_compare_and_swap_16'
/usr/bin/ld: rtl.o: in function `RtlInterlockedPushEntrySList':
/home/tux/Repos/hangover/build/wine-host/dlls/ntdll/../../../../wine/dlls/ntdll/rtl.c:121: undefined reference to `__sync_bool_compare_and_swap_16'
/usr/bin/ld: rtl.o: in function `_InterlockedCompareExchange128':
/home/tux/Repos/hangover/build/wine-host/dlls/ntdll/../../../../wine/dlls/ntdll/rtl.c:121: undefined reference to `__sync_bool_compare_and_swap_16'
/usr/bin/ld: rtl.o: in function `RtlInterlockedPushListSListEx':
/home/tux/Repos/hangover/build/wine-host/dlls/ntdll/../../../../wine/dlls/ntdll/rtl.c:121: undefined reference to `__sync_bool_compare_and_swap_16'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
make[2]: *** [Makefile:1564: ntdll.dll.so] Error 2
make[2]: Leaving directory '/home/tux/Repos/hangover/build/wine-host/dlls/ntdll'
make[1]: *** [Makefile:8951: dlls/ntdll] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by stefand** [comment]
This smells like a problem in upstream Wine. Can you try to build an unmodified wine, and if it fails the same way, report it on bugs.winehq.org?

**Comment by TuxThePenguin0** [comment]
A regular build of wine went fine although it refused to let me try and build unless I switched over to clang. Could that be the issue?

**Comment by stefand** [comment]
Right, yeah, that may have something to do with it. Hangover's makefile reads an envar  called HANGOVER_WINE_CC to allow you to specify a different compiler for the host-side wine, e.g.

HANGOVER_WINE_CC=clang make

Remove build/wine-host first though.

Hangover reverts Wine commit 8fb8cc03c3edb599dd98f369e14a08f899cbff95 because our asm helper function to call variadic functions currently implements the aarch64 Linux ABI, not the aarch64 Windows ABI. We need to fix this some day. As a result, the hangover host wine will not be able to execute aarch64 windows applications, but builds OK with gcc. After the last rebase I built with gcc 10, maybe older GCCs don't have the builtin intrinsics yet.

**Comment by TuxThePenguin0** [comment]
It hasn't finished building yet but it seems like compiling with clang fixed the error (it's up to compiling other sections with mingw)
So yeah it seems like GCC 9.2 is too old to compile Hangover at this point

**Comment by stefand** [comment]
Ya, it will compile an aarch64 wine, then an x86 Wine and an x86_64 Wine with mingw for some high level DLLs, then qemu, then the x86_64/x86 to aarch64 thunk DLLs. Lots of compiling. I'll close this bug and should remember to update the vararg asm pieces so I can remove the revert from Wine...

**Comment by yogo1212** [comment]
I'm sorry for the slight necrobump :-(

This might not be resolved. These builtins have been part of gcc for a long time.
There's a bug from 2009 [1] mentioning them and they are part of the documentation for gcc 4.1.2 [2].

The gcc-bug was solved by linking againt libgcc - but that fix is 10 years old now.
Clang build is running now because i want to see that juicy thing in action.
Afterwards, i'll try and see what can be done with gcc-9.2/-9.3.

Btw, @stefand do you and André have a tip jar?

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40134
[2] https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Atomic-Builtins.html
