### ISSUE TITLE
Using Windows Built-in DBT

### ISSUE THREAD

**Issue by vdaita** [AndreRH/hangover#77]
Hi,

The following blog states that there is a .dll file that does the emulation from x86 to ARM. Could that be used by hangover instead of QEMU?

https://threatvector.cylance.com/en_us/home/teardown-windows-10-on-arm-x86-emulation.html

**Comment by vdaita** [comment]
I don't really know much about this so I might be far off.

**Comment by stefand** [comment]
I don't think it is realistic no. Hangover's grand design would make it theoretically capable of running on Windows, if it weren't for a few hacks (see the diff in our wine tree vs winehq), but it probably makes some assumptions about DLL load order, PEB, TEB, etc pp that will make it unable to run. Likewise, Microsoft's solution probably uses lots of internal APIs, and/or depends on how native ntdll does the guest-host thunking. I don't know how it works on x86 on arm, but regular wow32on64 does userspace thunking before calling into the kernel, unlike things work in wine currently. I guess their x86 on arm will have similar differences.

The article you linked probably explains some details, but I don't want to read it for fear of being tainted with reverse engineered Windows internals.

I'll close this issue because it is a WONTFIX at this point and probably forever, but you're welcome to comment with thoughts.

**Comment by vdaita** [comment]
Has hangover tried HQEMU yet?

**Comment by stefand** [comment]
I haven't. I've heard of it, but not looked into it.

**Comment by stefand** [comment]
The qemu modifications outside windows-user/ are relatively small - they are mostly #ifdef changes to make it build with winelib and some hacks in the exception handling code and patching the windows-user/ stuff into the build system. Feel free to try and merge it into HQEMU :-)

**Comment by vdaita** [comment]
I haven’t had much luck with cross-compiling HQEMU so far for ARM64, but I’ll have another crack at it.
